#!/usr/bin/env bash
# Autocompletion for Python unittests
# Project: https://github.com/M0r13n/unittest-autocomp

_complete()
{
    local cmd="${1##*/}"
    local line="${COMP_LINE}"
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local completions=""

    # Quietly return nothing if the companion Python script is missing
    if ! command -v "unittest-autocomp" &> /dev/null
    then
        return
    fi

    # Check if the program was invoked as 'python -m unittest ...'
    case "$line" in
        *unittest*)
            completions="$( unittest-autocomp $cur )"
            ;;
        esac    

    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $( compgen -W "$completions" -- $cur ) )
}
complete -o default -o nospace -F _complete  python python3 python3.{3-11}
